name: CI Dev Deployment
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npm run build
          zip -r build.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | gh auth login --with-token

    - name: Release Dev Build
      env:
        TAG: ${{ vars.BUILD_TAG }}
        NOTE: ${{ vars.RELEASE_NOTE }}
      run: |
        gh release create "$TAG" build.zip --notes "$NOTE" --repo ${{ github.repository }}

